app = "rozare-evolution-api"
primary_region = "iad"

[build]
  image = "atendai/evolution-api:v2.1.0"

[env]
  SERVER_TYPE = "http"
  SERVER_PORT = "8080"
  AUTHENTICATION_API_KEY = "rozareplatform"
  AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES = "true"
  DATABASE_ENABLED = "true"
  DATABASE_PROVIDER = "postgresql"
  DATABASE_CONNECTION_CLIENT_NAME = "evolution"
  DATABASE_SAVE_DATA_INSTANCE = "true"
  DATABASE_SAVE_DATA_NEW_MESSAGE = "false"
  DATABASE_SAVE_MESSAGE_UPDATE = "false"
  DATABASE_SAVE_DATA_CONTACTS = "false"
  DATABASE_SAVE_DATA_CHATS = "false"
  CACHE_REDIS_ENABLED = "false"
  CACHE_REDIS_URI = ""
  CACHE_LOCAL_ENABLED = "false"
  CONFIG_SESSION_PHONE_CLIENT = "Rozare"
  CONFIG_SESSION_PHONE_NAME = "Chrome"
  QRCODE_LIMIT = "30"
  QRCODE_COLOR = "#000000"
  LOG_LEVEL = "DEBUG"
  LOG_COLOR = "true"
  DEL_INSTANCE = "false"
  WEBHOOK_GLOBAL_ENABLED = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
